//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBSC.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprestimo
    {
        public Emprestimo()
        {
            this.ItensEmprestimo = new HashSet<ItemEmprestimo>();
        }
    
        public int Id { get; set; }
        public int Id_Pessoa { get; set; }
        public System.DateTime DtEmprestimo { get; set; }
        public Nullable<System.DateTime> DtPrevisaoDevolucao { get; set; }
        public byte Status { get; set; }
        public System.DateTime DtHrCadastro { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual ICollection<ItemEmprestimo> ItensEmprestimo { get; set; }
    }
}
