//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBSC.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public Livro()
        {
            this.ItensEmprestimo = new HashSet<ItemEmprestimo>();
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Titulo { get; set; }
        public string Genero { get; set; }
        public string Autor { get; set; }
        public string Editora { get; set; }
        public Nullable<int> Ano { get; set; }
        public byte EstadoConservacao { get; set; }
        public string Local { get; set; }
        public string Resumo { get; set; }
        public bool IsBaixado { get; set; }
        public Nullable<System.DateTime> DtBaixa { get; set; }
        public System.DateTime DtHrCadastro { get; set; }
        public Nullable<System.DateTime> DtHrEdicao { get; set; }
    
        public virtual ICollection<ItemEmprestimo> ItensEmprestimo { get; set; }
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
