//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBSC.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Emprestimos = new HashSet<Emprestimo>();
            this.Reservas = new HashSet<Reserva>();
        }
    
        public int Id { get; set; }
        public byte Tipo { get; set; }
        public Nullable<byte> Sexo { get; set; }
        public string CodigoMatricula { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public string Cidade { get; set; }
        public Nullable<int> UF { get; set; }
        public string Telefone { get; set; }
        public bool IsSistema { get; set; }
        public System.DateTime DtHrCadastro { get; set; }
        public Nullable<System.DateTime> DtHrEdicao { get; set; }
    
        public virtual ICollection<Emprestimo> Emprestimos { get; set; }
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}
